name: Deploy agent, Qdrant to AKS Cluster
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d agent
