name: Dummy GitHub Actions Workflow

on: [push]

jobs:
  dummy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"